# Site settings
title: "Mariner OS"
description: Linux for Cloud and Edge
owner: Microsoft COSINE EdgeOS
first_published: 2020
email: MarinerAdmins@micrsoft.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "mariner" # the base hostname & protocol for your site
logo: "images/mariner.png"
icon: "images/mariner.png"
social:
  github: https://github.com/microsoft/MarinerSite

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman