# Site settings
title: "Amye + Jim"
description: |
    Portland, Oregon

    July 18, 2019
owner: Jim and Amye
first_published: 2019
email: wedding@msamye.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "scavarda-perr.in" # the base hostname & protocol for your site

social:
  github: https://github.com/scavarda-perrin/scavarda-perrin.github.io/

# Build settings
markdown: kramdown
